-- BASE DE DONNÉES DU CHAMPIONAT DE FRANCE FÉMININ DE FOOTBALL
-- LES DONNÉES SONT TIRÉES UNIQUEMENT DE SOURCES PUBLIQUES
-- COMME WIKIPEDIA OU LES SITES INTERNET DES CLUBS MENTIONNÉS.

SELECT nom From Equipes;
