-- BASE DE DONNÉES DU CHAMPIONNAT DE FRANCE FÉMININ DE FOOTBALL
-- LES DONNÉES SONT TIRÉES UNIQUEMENT DE SOURCES PUBLIQUES
-- COMME WIKIPEDIA, LE SITE DE LA FFF ET LES SITES INTERNET
-- DES CLUBS MENTIONNÉS.

SELECT nom From Equipe;
